version: '3.7'

services:
   dashboard-plotly-rushclin:
     build: 
       context: ./../../modules/rushclin/src/frontend/python
     restart: always
     ports:
       - 5002:8050
     networks:
       - network 
    
networks:
  network:
    driver: bridge