version: '3.7'

services:
   dashboard-plotly-morritz:
     build: 
       context: ./../../modules/morritz/src/frontend/python
     restart: always
     ports:
       - 5000:4000
       - 5001:4001
       - 5002:4002
     networks:
       - network 
    
networks:
  network:
    driver: bridge