version: '3.7'

services:
   dashboard-plotly-maestros:
     build: 
       context: ./../../modules/maestros/src/frontend/python
     restart: always
     ports:
       - 5000:8050
     networks:
       - network 
    
networks:
  network:
    driver: bridge