version: '3.7'

services:
   dashboard-plotly-morritz:
     build: 
       context: ./../../modules/morritz/src/frontend/python
     restart: always
     ports:
       - 5001:8050
     networks:
       - network 
    
networks:
  network:
    driver: bridge